# Generated by Django 2.2 on 2020-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('shape', models.CharField(choices=[('REC', 'Прямоугольный, квадратный'), ('OVL', 'Овальный, круглый')], default='REC', max_length=3)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
