# Generated by Django 2.2 on 2020-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_order']},
        ),
        migrations.AddField(
            model_name='table',
            name='center_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='table',
            name='center_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='table',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
